create table tb_city (id bigint not null auto_increment, name varchar(255) not null, state_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_group (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_group_permission (group_id bigint not null, permission_id bigint not null) engine=InnoDB;
create table tb_kitchen (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_payment_method (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_permission (id bigint not null auto_increment, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_product (id bigint not null auto_increment, active bit not null, description varchar(255) not null, name varchar(255) not null, price decimal(19,2), restaurant_id bigint, primary key (id)) engine=InnoDB;
create table tb_restaurant (id bigint not null auto_increment, address_address varchar(255), address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_zip_code varchar(255), freight_tax decimal(19,2) not null, last_update_date datetime not null, name varchar(255) not null, register_date datetime not null, address_city_id bigint, kitchen_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_restaurant_payment_method (restaurant_id bigint not null, payment_method_id bigint not null) engine=InnoDB;
create table tb_state (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, mail varchar(255) not null, name varchar(255) not null, password varchar(255) not null, register_date datetime not null, primary key (id)) engine=InnoDB;
create table tb_user_group (user_id bigint not null, group_id bigint not null) engine=InnoDB;
alter table tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state (id);
alter table tb_group_permission add constraint FKc2rc154h8udl1bmo76luik7jj foreign key (permission_id) references tb_permission (id);
alter table tb_group_permission add constraint FKfabw19737lr4x9u74m9bhs9cx foreign key (group_id) references tb_group (id);
alter table tb_product add constraint FKsaq6oeo2b1pkq49bjacej31k2 foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_restaurant add constraint FK61k02rmf9ud5lu2rdde3ofblh foreign key (address_city_id) references tb_city (id);
alter table tb_restaurant add constraint FKo4yy82dlq4ig3ebquw7ojjjwp foreign key (kitchen_id) references tb_kitchen (id);
alter table tb_restaurant_payment_method add constraint FK943afhe0bxmfbxycnm1jwtas7 foreign key (payment_method_id) references tb_payment_method (id);
alter table tb_restaurant_payment_method add constraint FK14uaqf86qejtt97qoxxnx8bup foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_user_group add constraint FKid96lv86ri5sahn1i5vfutj7u foreign key (group_id) references tb_group (id);
alter table tb_user_group add constraint FK2jb7cj4c0qrsqutdjr9wpuo6l foreign key (user_id) references tb_user (id);
create table tb_city (id bigint not null auto_increment, name varchar(255) not null, state_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_group (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_group_permission (group_id bigint not null, permission_id bigint not null) engine=InnoDB;
create table tb_kitchen (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_payment_method (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_permission (id bigint not null auto_increment, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_product (id bigint not null auto_increment, active bit not null, description varchar(255) not null, name varchar(255) not null, price decimal(19,2), restaurant_id bigint, primary key (id)) engine=InnoDB;
create table tb_restaurant (id bigint not null auto_increment, address_address varchar(255), address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_zip_code varchar(255), freight_tax decimal(19,2) not null, last_update_date datetime not null, name varchar(255) not null, register_date datetime not null, address_city_id bigint, kitchen_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_restaurant_payment_method (restaurant_id bigint not null, payment_method_id bigint not null) engine=InnoDB;
create table tb_state (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, mail varchar(255) not null, name varchar(255) not null, password varchar(255) not null, register_date datetime not null, primary key (id)) engine=InnoDB;
create table tb_user_group (user_id bigint not null, group_id bigint not null) engine=InnoDB;
alter table tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state (id);
alter table tb_group_permission add constraint FKc2rc154h8udl1bmo76luik7jj foreign key (permission_id) references tb_permission (id);
alter table tb_group_permission add constraint FKfabw19737lr4x9u74m9bhs9cx foreign key (group_id) references tb_group (id);
alter table tb_product add constraint FKsaq6oeo2b1pkq49bjacej31k2 foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_restaurant add constraint FK61k02rmf9ud5lu2rdde3ofblh foreign key (address_city_id) references tb_city (id);
alter table tb_restaurant add constraint FKo4yy82dlq4ig3ebquw7ojjjwp foreign key (kitchen_id) references tb_kitchen (id);
alter table tb_restaurant_payment_method add constraint FK943afhe0bxmfbxycnm1jwtas7 foreign key (payment_method_id) references tb_payment_method (id);
alter table tb_restaurant_payment_method add constraint FK14uaqf86qejtt97qoxxnx8bup foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_user_group add constraint FKid96lv86ri5sahn1i5vfutj7u foreign key (group_id) references tb_group (id);
alter table tb_user_group add constraint FK2jb7cj4c0qrsqutdjr9wpuo6l foreign key (user_id) references tb_user (id);
create table tb_city (id bigint not null auto_increment, name varchar(255) not null, state_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_group (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_group_permission (group_id bigint not null, permission_id bigint not null) engine=InnoDB;
create table tb_kitchen (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_payment_method (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_permission (id bigint not null auto_increment, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_product (id bigint not null auto_increment, active bit not null, description varchar(255) not null, name varchar(255) not null, price decimal(19,2), restaurant_id bigint, primary key (id)) engine=InnoDB;
create table tb_restaurant (id bigint not null auto_increment, address_address varchar(255), address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_zip_code varchar(255), freight_tax decimal(19,2) not null, last_update_date datetime not null, name varchar(255) not null, register_date datetime not null, address_city_id bigint, kitchen_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_restaurant_payment_method (restaurant_id bigint not null, payment_method_id bigint not null) engine=InnoDB;
create table tb_state (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, mail varchar(255) not null, name varchar(255) not null, password varchar(255) not null, register_date datetime not null, primary key (id)) engine=InnoDB;
create table tb_user_group (user_id bigint not null, group_id bigint not null) engine=InnoDB;
alter table tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state (id);
alter table tb_group_permission add constraint FKc2rc154h8udl1bmo76luik7jj foreign key (permission_id) references tb_permission (id);
alter table tb_group_permission add constraint FKfabw19737lr4x9u74m9bhs9cx foreign key (group_id) references tb_group (id);
alter table tb_product add constraint FKsaq6oeo2b1pkq49bjacej31k2 foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_restaurant add constraint FK61k02rmf9ud5lu2rdde3ofblh foreign key (address_city_id) references tb_city (id);
alter table tb_restaurant add constraint FKo4yy82dlq4ig3ebquw7ojjjwp foreign key (kitchen_id) references tb_kitchen (id);
alter table tb_restaurant_payment_method add constraint FK943afhe0bxmfbxycnm1jwtas7 foreign key (payment_method_id) references tb_payment_method (id);
alter table tb_restaurant_payment_method add constraint FK14uaqf86qejtt97qoxxnx8bup foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_user_group add constraint FKid96lv86ri5sahn1i5vfutj7u foreign key (group_id) references tb_group (id);
alter table tb_user_group add constraint FK2jb7cj4c0qrsqutdjr9wpuo6l foreign key (user_id) references tb_user (id);
create table tb_city (id bigint not null auto_increment, name varchar(255) not null, state_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_group (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_group_permission (group_id bigint not null, permission_id bigint not null) engine=InnoDB;
create table tb_kitchen (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_payment_method (id bigint not null auto_increment, description varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_permission (id bigint not null auto_increment, description varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_product (id bigint not null auto_increment, active bit not null, description varchar(255) not null, name varchar(255) not null, price decimal(19,2), restaurant_id bigint, primary key (id)) engine=InnoDB;
create table tb_restaurant (id bigint not null auto_increment, address_address varchar(255), address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_zip_code varchar(255), freight_tax decimal(19,2) not null, last_update_date datetime not null, name varchar(255) not null, register_date datetime not null, address_city_id bigint, kitchen_id bigint not null, primary key (id)) engine=InnoDB;
create table tb_restaurant_payment_method (restaurant_id bigint not null, payment_method_id bigint not null) engine=InnoDB;
create table tb_state (id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_user (id bigint not null auto_increment, mail varchar(255) not null, name varchar(255) not null, password varchar(255) not null, register_date datetime not null, primary key (id)) engine=InnoDB;
create table tb_user_group (user_id bigint not null, group_id bigint not null) engine=InnoDB;
alter table tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state (id);
alter table tb_group_permission add constraint FKc2rc154h8udl1bmo76luik7jj foreign key (permission_id) references tb_permission (id);
alter table tb_group_permission add constraint FKfabw19737lr4x9u74m9bhs9cx foreign key (group_id) references tb_group (id);
alter table tb_product add constraint FKsaq6oeo2b1pkq49bjacej31k2 foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_restaurant add constraint FK61k02rmf9ud5lu2rdde3ofblh foreign key (address_city_id) references tb_city (id);
alter table tb_restaurant add constraint FKo4yy82dlq4ig3ebquw7ojjjwp foreign key (kitchen_id) references tb_kitchen (id);
alter table tb_restaurant_payment_method add constraint FK943afhe0bxmfbxycnm1jwtas7 foreign key (payment_method_id) references tb_payment_method (id);
alter table tb_restaurant_payment_method add constraint FK14uaqf86qejtt97qoxxnx8bup foreign key (restaurant_id) references tb_restaurant (id);
alter table tb_user_group add constraint FKid96lv86ri5sahn1i5vfutj7u foreign key (group_id) references tb_group (id);
alter table tb_user_group add constraint FK2jb7cj4c0qrsqutdjr9wpuo6l foreign key (user_id) references tb_user (id);
